"""add_mutation_target_name

Revision ID: 664d50922605
Revises: 841b8d816121
Create Date: 2026-06-07 22:09:44.355257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '664d50922605'
down_revision: Union[str, Sequence[str], None] = '841b8d816121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mutation', sa.Column('target_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mutation', 'target_name')
    # ### end Alembic commands ###
