"""add_mutation_lifecycle_and_version_tracking

Revision ID: 841b8d816121
Revises: 9778bcea0cd6
Create Date: 2026-06-07 22:07:41.327674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841b8d816121'
down_revision: Union[str, Sequence[str], None] = '9778bcea0cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mutation', sa.Column('base_version_id', sa.Integer(), nullable=True))
    op.add_column('mutation', sa.Column('candidate_version_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('mutation', schema=None) as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.VARCHAR(length=8),
                   type_=sa.Enum('proposed', 'pending', 'candidate', 'evaluating', 'promoted', 'active', 'reverted', 'rejected', 'rolled_back', name='mutationstatus'),
                   existing_nullable=False)
    op.add_column('task', sa.Column('harness_version_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'harness_version_id')
    with op.batch_alter_table('mutation', schema=None) as batch_op:
        batch_op.alter_column('status',
                   existing_type=sa.Enum('proposed', 'pending', 'candidate', 'evaluating', 'promoted', 'active', 'reverted', 'rejected', 'rolled_back', name='mutationstatus'),
                   type_=sa.VARCHAR(length=8),
                   existing_nullable=False)
    op.drop_column('mutation', 'candidate_version_id')
    op.drop_column('mutation', 'base_version_id')
    # ### end Alembic commands ###
