"""initial_schema

Revision ID: 9778bcea0cd6
Revises: 
Create Date: 2026-06-07 22:06:31.513270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9778bcea0cd6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_spec', sa.JSON(), nullable=True),
    sa.Column('assertion', sa.JSON(), nullable=True),
    sa.Column('origin', sa.Enum('seed', 'auto', name='benchmarkorigin'), nullable=False),
    sa.Column('created_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benchmark_name'), 'benchmark', ['name'], unique=True)
    op.create_table('harnessversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_set', sa.JSON(), nullable=True),
    sa.Column('tool_set', sa.JSON(), nullable=True),
    sa.Column('strategy_set', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mutation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('prompt', 'tool', 'strategy', name='mutationkind'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'reverted', 'rejected', name='mutationstatus'), nullable=False),
    sa.Column('benchmark_delta', sa.Float(), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=False),
    sa.Column('decided_ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('system', 'planner', 'recovery', 'meta', 'discovery', name='promptrole'), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('active', 'candidate', 'archived', name='promptstatus'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('active', 'candidate', 'archived', name='strategystatus'), nullable=False),
    sa.Column('created_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_key'), 'strategy', ['key'], unique=True)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('user_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('running', 'success', 'failed', name='taskstatus'), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('sandbox_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('final_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('analyzed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_user_prompt'), 'task', ['user_prompt'], unique=False)
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('json_schema', sa.JSON(), nullable=True),
    sa.Column('implementation_kind', sa.Enum('builtin', 'python_code', name='toolkind'), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('active', 'deprecated', name='toolstatus'), nullable=False),
    sa.Column('created_ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_name'), 'tool', ['name'], unique=True)
    op.create_table('benchmarkrun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('benchmark_id', sa.Integer(), nullable=False),
    sa.Column('harness_version', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmark.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('plan', 'tool_call', 'observation', 'final', name='steptype'), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toolcall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toolcall')
    op.drop_table('step')
    op.drop_table('benchmarkrun')
    op.drop_index(op.f('ix_tool_name'), table_name='tool')
    op.drop_table('tool')
    op.drop_index(op.f('ix_task_user_prompt'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_strategy_key'), table_name='strategy')
    op.drop_table('strategy')
    op.drop_table('prompt')
    op.drop_table('mutation')
    op.drop_table('harnessversion')
    op.drop_index(op.f('ix_benchmark_name'), table_name='benchmark')
    op.drop_table('benchmark')
    # ### end Alembic commands ###
