"""add_task_category_and_trace_id

Revision ID: bdfabafa9f67
Revises: c08fb9266eb4
Create Date: 2026-06-07 22:47:04.835771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bdfabafa9f67'
down_revision: Union[str, Sequence[str], None] = 'c08fb9266eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('category', sa.Enum('user', 'benchmark', 'system', name='taskcategory'), nullable=False))
    op.add_column('task', sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_task_trace_id'), 'task', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_trace_id'), table_name='task')
    op.drop_column('task', 'trace_id')
    op.drop_column('task', 'category')
    # ### end Alembic commands ###
