"""remove_tool_name_unique_constraint

Revision ID: c08fb9266eb4
Revises: 664d50922605
Create Date: 2026-06-07 22:34:42.211850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c08fb9266eb4'
down_revision: Union[str, Sequence[str], None] = '664d50922605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_name'), table_name='tool')
    op.create_index(op.f('ix_tool_name'), 'tool', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_name'), table_name='tool')
    op.create_index(op.f('ix_tool_name'), 'tool', ['name'], unique=1)
    # ### end Alembic commands ###
